[package]
name = "lua"
version = "0.1.0"
edition = "2021"
build = "build.rs" # LALRPOP preprocessing

[dependencies]
lalrpop-util = "0.19.9"
logos = "0.13.0"
itertools = "0.10.5"

[build-dependencies]
lalrpop = "0.19.9"
